apiVersion: v1
kind: Service
metadata:
  name: prometheus-global
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30901
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
